<?php
/**
 * AddressesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * AddressesApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddressesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createAddress' => [
            'application/json',
        ],
        'getAddress' => [
            'application/json',
        ],
        'listAddresses' => [
            'application/json',
        ],
        'validateAddress' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createAddress
     *
     * Create a new address
     *
     * @param  \OpenAPI\Client\Model\AddressCreateRequest $address_create_request Address details. (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddress'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Address|array<string,mixed>
     */
    public function createAddress($address_create_request, $shippo_api_version = null, string $contentType = self::contentTypes['createAddress'][0])
    {
        list($response) = $this->createAddressWithHttpInfo($address_create_request, $shippo_api_version, $contentType);
        return $response;
    }

    /**
     * Operation createAddressWithHttpInfo
     *
     * Create a new address
     *
     * @param  \OpenAPI\Client\Model\AddressCreateRequest $address_create_request Address details. (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddress'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Address|array<string,mixed>, HTTP status code, HTTP response headers (array of strings)
     */
    public function createAddressWithHttpInfo($address_create_request, $shippo_api_version = null, string $contentType = self::contentTypes['createAddress'][0])
    {
        $request = $this->createAddressRequest($address_create_request, $shippo_api_version, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\Address',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        'array<string,mixed>',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\Address',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Address',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,mixed>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createAddressAsync
     *
     * Create a new address
     *
     * @param  \OpenAPI\Client\Model\AddressCreateRequest $address_create_request Address details. (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAddressAsync($address_create_request, $shippo_api_version = null, string $contentType = self::contentTypes['createAddress'][0])
    {
        return $this->createAddressAsyncWithHttpInfo($address_create_request, $shippo_api_version, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createAddressAsyncWithHttpInfo
     *
     * Create a new address
     *
     * @param  \OpenAPI\Client\Model\AddressCreateRequest $address_create_request Address details. (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAddressAsyncWithHttpInfo($address_create_request, $shippo_api_version = null, string $contentType = self::contentTypes['createAddress'][0])
    {
        $returnType = '\OpenAPI\Client\Model\Address';
        $request = $this->createAddressRequest($address_create_request, $shippo_api_version, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createAddress'
     *
     * @param  \OpenAPI\Client\Model\AddressCreateRequest $address_create_request Address details. (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createAddressRequest($address_create_request, $shippo_api_version = null, string $contentType = self::contentTypes['createAddress'][0])
    {

        // verify the required parameter 'address_create_request' is set
        if ($address_create_request === null || (is_array($address_create_request) && count($address_create_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $address_create_request when calling createAddress'
            );
        }



        $resourcePath = '/addresses';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($shippo_api_version !== null) {
            $headerParams['SHIPPO-API-VERSION'] = ObjectSerializer::toHeaderValue($shippo_api_version);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($address_create_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($address_create_request));
            } else {
                $httpBody = $address_create_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAddress
     *
     * Retrieve an address
     *
     * @param  string $address_id Object ID of the address (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAddress'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Address|array<string,mixed>
     */
    public function getAddress($address_id, $shippo_api_version = null, string $contentType = self::contentTypes['getAddress'][0])
    {
        list($response) = $this->getAddressWithHttpInfo($address_id, $shippo_api_version, $contentType);
        return $response;
    }

    /**
     * Operation getAddressWithHttpInfo
     *
     * Retrieve an address
     *
     * @param  string $address_id Object ID of the address (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAddress'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Address|array<string,mixed>, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAddressWithHttpInfo($address_id, $shippo_api_version = null, string $contentType = self::contentTypes['getAddress'][0])
    {
        $request = $this->getAddressRequest($address_id, $shippo_api_version, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\Address',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        'array<string,mixed>',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\Address',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Address',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,mixed>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAddressAsync
     *
     * Retrieve an address
     *
     * @param  string $address_id Object ID of the address (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAddressAsync($address_id, $shippo_api_version = null, string $contentType = self::contentTypes['getAddress'][0])
    {
        return $this->getAddressAsyncWithHttpInfo($address_id, $shippo_api_version, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAddressAsyncWithHttpInfo
     *
     * Retrieve an address
     *
     * @param  string $address_id Object ID of the address (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAddressAsyncWithHttpInfo($address_id, $shippo_api_version = null, string $contentType = self::contentTypes['getAddress'][0])
    {
        $returnType = '\OpenAPI\Client\Model\Address';
        $request = $this->getAddressRequest($address_id, $shippo_api_version, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAddress'
     *
     * @param  string $address_id Object ID of the address (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAddressRequest($address_id, $shippo_api_version = null, string $contentType = self::contentTypes['getAddress'][0])
    {

        // verify the required parameter 'address_id' is set
        if ($address_id === null || (is_array($address_id) && count($address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $address_id when calling getAddress'
            );
        }



        $resourcePath = '/addresses/{AddressId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($shippo_api_version !== null) {
            $headerParams['SHIPPO-API-VERSION'] = ObjectSerializer::toHeaderValue($shippo_api_version);
        }

        // path params
        if ($address_id !== null) {
            $resourcePath = str_replace(
                '{' . 'AddressId' . '}',
                ObjectSerializer::toPathValue($address_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listAddresses
     *
     * List all addresses
     *
     * @param  int|null $page The page number you want to select (optional, default to 1)
     * @param  int|null $results The number of results to return per page (max 100, default 5) (optional, default to 5)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAddresses'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\AddressPaginatedList|array<string,mixed>
     */
    public function listAddresses($page = 1, $results = 5, $shippo_api_version = null, string $contentType = self::contentTypes['listAddresses'][0])
    {
        list($response) = $this->listAddressesWithHttpInfo($page, $results, $shippo_api_version, $contentType);
        return $response;
    }

    /**
     * Operation listAddressesWithHttpInfo
     *
     * List all addresses
     *
     * @param  int|null $page The page number you want to select (optional, default to 1)
     * @param  int|null $results The number of results to return per page (max 100, default 5) (optional, default to 5)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAddresses'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\AddressPaginatedList|array<string,mixed>, HTTP status code, HTTP response headers (array of strings)
     */
    public function listAddressesWithHttpInfo($page = 1, $results = 5, $shippo_api_version = null, string $contentType = self::contentTypes['listAddresses'][0])
    {
        $request = $this->listAddressesRequest($page, $results, $shippo_api_version, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\AddressPaginatedList',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        'array<string,mixed>',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\AddressPaginatedList',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\AddressPaginatedList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,mixed>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listAddressesAsync
     *
     * List all addresses
     *
     * @param  int|null $page The page number you want to select (optional, default to 1)
     * @param  int|null $results The number of results to return per page (max 100, default 5) (optional, default to 5)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAddresses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAddressesAsync($page = 1, $results = 5, $shippo_api_version = null, string $contentType = self::contentTypes['listAddresses'][0])
    {
        return $this->listAddressesAsyncWithHttpInfo($page, $results, $shippo_api_version, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listAddressesAsyncWithHttpInfo
     *
     * List all addresses
     *
     * @param  int|null $page The page number you want to select (optional, default to 1)
     * @param  int|null $results The number of results to return per page (max 100, default 5) (optional, default to 5)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAddresses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAddressesAsyncWithHttpInfo($page = 1, $results = 5, $shippo_api_version = null, string $contentType = self::contentTypes['listAddresses'][0])
    {
        $returnType = '\OpenAPI\Client\Model\AddressPaginatedList';
        $request = $this->listAddressesRequest($page, $results, $shippo_api_version, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listAddresses'
     *
     * @param  int|null $page The page number you want to select (optional, default to 1)
     * @param  int|null $results The number of results to return per page (max 100, default 5) (optional, default to 5)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAddresses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listAddressesRequest($page = 1, $results = 5, $shippo_api_version = null, string $contentType = self::contentTypes['listAddresses'][0])
    {


        if ($results !== null && $results > 100) {
            throw new \InvalidArgumentException('invalid value for "$results" when calling AddressesApi.listAddresses, must be smaller than or equal to 100.');
        }
        


        $resourcePath = '/addresses';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $results,
            'results', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($shippo_api_version !== null) {
            $headerParams['SHIPPO-API-VERSION'] = ObjectSerializer::toHeaderValue($shippo_api_version);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation validateAddress
     *
     * Validate an address
     *
     * @param  string $address_id Object ID of the address (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateAddress'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Address|array<string,mixed>
     */
    public function validateAddress($address_id, $shippo_api_version = null, string $contentType = self::contentTypes['validateAddress'][0])
    {
        list($response) = $this->validateAddressWithHttpInfo($address_id, $shippo_api_version, $contentType);
        return $response;
    }

    /**
     * Operation validateAddressWithHttpInfo
     *
     * Validate an address
     *
     * @param  string $address_id Object ID of the address (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateAddress'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Address|array<string,mixed>, HTTP status code, HTTP response headers (array of strings)
     */
    public function validateAddressWithHttpInfo($address_id, $shippo_api_version = null, string $contentType = self::contentTypes['validateAddress'][0])
    {
        $request = $this->validateAddressRequest($address_id, $shippo_api_version, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\Address',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        'array<string,mixed>',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\Address',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Address',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,mixed>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation validateAddressAsync
     *
     * Validate an address
     *
     * @param  string $address_id Object ID of the address (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function validateAddressAsync($address_id, $shippo_api_version = null, string $contentType = self::contentTypes['validateAddress'][0])
    {
        return $this->validateAddressAsyncWithHttpInfo($address_id, $shippo_api_version, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation validateAddressAsyncWithHttpInfo
     *
     * Validate an address
     *
     * @param  string $address_id Object ID of the address (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function validateAddressAsyncWithHttpInfo($address_id, $shippo_api_version = null, string $contentType = self::contentTypes['validateAddress'][0])
    {
        $returnType = '\OpenAPI\Client\Model\Address';
        $request = $this->validateAddressRequest($address_id, $shippo_api_version, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'validateAddress'
     *
     * @param  string $address_id Object ID of the address (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function validateAddressRequest($address_id, $shippo_api_version = null, string $contentType = self::contentTypes['validateAddress'][0])
    {

        // verify the required parameter 'address_id' is set
        if ($address_id === null || (is_array($address_id) && count($address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $address_id when calling validateAddress'
            );
        }



        $resourcePath = '/addresses/{AddressId}/validate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($shippo_api_version !== null) {
            $headerParams['SHIPPO-API-VERSION'] = ObjectSerializer::toHeaderValue($shippo_api_version);
        }

        // path params
        if ($address_id !== null) {
            $resourcePath = str_replace(
                '{' . 'AddressId' . '}',
                ObjectSerializer::toPathValue($address_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
