<?php
/**
 * OrdersApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * OrdersApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrdersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createOrder' => [
            'application/json',
        ],
        'getOrder' => [
            'application/json',
        ],
        'listOrders' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createOrder
     *
     * Create a new order
     *
     * @param  \OpenAPI\Client\Model\OrderCreateRequest $order_create_request Order details. (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createOrder'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Order|array<string,mixed>
     */
    public function createOrder($order_create_request, $shippo_api_version = null, string $contentType = self::contentTypes['createOrder'][0])
    {
        list($response) = $this->createOrderWithHttpInfo($order_create_request, $shippo_api_version, $contentType);
        return $response;
    }

    /**
     * Operation createOrderWithHttpInfo
     *
     * Create a new order
     *
     * @param  \OpenAPI\Client\Model\OrderCreateRequest $order_create_request Order details. (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createOrder'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Order|array<string,mixed>, HTTP status code, HTTP response headers (array of strings)
     */
    public function createOrderWithHttpInfo($order_create_request, $shippo_api_version = null, string $contentType = self::contentTypes['createOrder'][0])
    {
        $request = $this->createOrderRequest($order_create_request, $shippo_api_version, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\Order',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        'array<string,mixed>',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\Order',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Order',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,mixed>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createOrderAsync
     *
     * Create a new order
     *
     * @param  \OpenAPI\Client\Model\OrderCreateRequest $order_create_request Order details. (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createOrderAsync($order_create_request, $shippo_api_version = null, string $contentType = self::contentTypes['createOrder'][0])
    {
        return $this->createOrderAsyncWithHttpInfo($order_create_request, $shippo_api_version, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createOrderAsyncWithHttpInfo
     *
     * Create a new order
     *
     * @param  \OpenAPI\Client\Model\OrderCreateRequest $order_create_request Order details. (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createOrderAsyncWithHttpInfo($order_create_request, $shippo_api_version = null, string $contentType = self::contentTypes['createOrder'][0])
    {
        $returnType = '\OpenAPI\Client\Model\Order';
        $request = $this->createOrderRequest($order_create_request, $shippo_api_version, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createOrder'
     *
     * @param  \OpenAPI\Client\Model\OrderCreateRequest $order_create_request Order details. (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createOrderRequest($order_create_request, $shippo_api_version = null, string $contentType = self::contentTypes['createOrder'][0])
    {

        // verify the required parameter 'order_create_request' is set
        if ($order_create_request === null || (is_array($order_create_request) && count($order_create_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_create_request when calling createOrder'
            );
        }



        $resourcePath = '/orders';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($shippo_api_version !== null) {
            $headerParams['SHIPPO-API-VERSION'] = ObjectSerializer::toHeaderValue($shippo_api_version);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($order_create_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($order_create_request));
            } else {
                $httpBody = $order_create_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getOrder
     *
     * Retrieve an order
     *
     * @param  string $order_id Object ID of the order (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrder'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Order|array<string,mixed>
     */
    public function getOrder($order_id, $shippo_api_version = null, string $contentType = self::contentTypes['getOrder'][0])
    {
        list($response) = $this->getOrderWithHttpInfo($order_id, $shippo_api_version, $contentType);
        return $response;
    }

    /**
     * Operation getOrderWithHttpInfo
     *
     * Retrieve an order
     *
     * @param  string $order_id Object ID of the order (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrder'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Order|array<string,mixed>, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOrderWithHttpInfo($order_id, $shippo_api_version = null, string $contentType = self::contentTypes['getOrder'][0])
    {
        $request = $this->getOrderRequest($order_id, $shippo_api_version, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\Order',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        'array<string,mixed>',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\Order',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Order',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,mixed>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getOrderAsync
     *
     * Retrieve an order
     *
     * @param  string $order_id Object ID of the order (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrderAsync($order_id, $shippo_api_version = null, string $contentType = self::contentTypes['getOrder'][0])
    {
        return $this->getOrderAsyncWithHttpInfo($order_id, $shippo_api_version, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOrderAsyncWithHttpInfo
     *
     * Retrieve an order
     *
     * @param  string $order_id Object ID of the order (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrderAsyncWithHttpInfo($order_id, $shippo_api_version = null, string $contentType = self::contentTypes['getOrder'][0])
    {
        $returnType = '\OpenAPI\Client\Model\Order';
        $request = $this->getOrderRequest($order_id, $shippo_api_version, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOrder'
     *
     * @param  string $order_id Object ID of the order (required)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getOrderRequest($order_id, $shippo_api_version = null, string $contentType = self::contentTypes['getOrder'][0])
    {

        // verify the required parameter 'order_id' is set
        if ($order_id === null || (is_array($order_id) && count($order_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_id when calling getOrder'
            );
        }



        $resourcePath = '/orders/{OrderId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($shippo_api_version !== null) {
            $headerParams['SHIPPO-API-VERSION'] = ObjectSerializer::toHeaderValue($shippo_api_version);
        }

        // path params
        if ($order_id !== null) {
            $resourcePath = str_replace(
                '{' . 'OrderId' . '}',
                ObjectSerializer::toPathValue($order_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listOrders
     *
     * List all orders
     *
     * @param  int|null $page The page number you want to select (optional, default to 1)
     * @param  int|null $results The number of results to return per page (max 100) (optional, default to 25)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  \OpenAPI\Client\Model\OrderStatusEnum[]|null $order_status Filter orders by order status (optional)
     * @param  \OpenAPI\Client\Model\OrderShopAppEnum|null $shop_app Filter orders by shop app (optional)
     * @param  string|null $start_date Filter orders created after the input date and time (ISO 8601 UTC format).  This is based on the  &#x60;placed_at&#x60; field, meaning when the order has been placed, not when the order object was created. (optional)
     * @param  string|null $end_date Filter orders created before the input date and time (ISO 8601 UTC format).  This is based on the  &#x60;placed_at&#x60; field, meaning when the order has been placed, not when the order object was created. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listOrders'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\OrderPaginatedList|array<string,mixed>
     */
    public function listOrders($page = 1, $results = 25, $shippo_api_version = null, $order_status = null, $shop_app = null, $start_date = null, $end_date = null, string $contentType = self::contentTypes['listOrders'][0])
    {
        list($response) = $this->listOrdersWithHttpInfo($page, $results, $shippo_api_version, $order_status, $shop_app, $start_date, $end_date, $contentType);
        return $response;
    }

    /**
     * Operation listOrdersWithHttpInfo
     *
     * List all orders
     *
     * @param  int|null $page The page number you want to select (optional, default to 1)
     * @param  int|null $results The number of results to return per page (max 100) (optional, default to 25)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  \OpenAPI\Client\Model\OrderStatusEnum[]|null $order_status Filter orders by order status (optional)
     * @param  \OpenAPI\Client\Model\OrderShopAppEnum|null $shop_app Filter orders by shop app (optional)
     * @param  string|null $start_date Filter orders created after the input date and time (ISO 8601 UTC format).  This is based on the  &#x60;placed_at&#x60; field, meaning when the order has been placed, not when the order object was created. (optional)
     * @param  string|null $end_date Filter orders created before the input date and time (ISO 8601 UTC format).  This is based on the  &#x60;placed_at&#x60; field, meaning when the order has been placed, not when the order object was created. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listOrders'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\OrderPaginatedList|array<string,mixed>, HTTP status code, HTTP response headers (array of strings)
     */
    public function listOrdersWithHttpInfo($page = 1, $results = 25, $shippo_api_version = null, $order_status = null, $shop_app = null, $start_date = null, $end_date = null, string $contentType = self::contentTypes['listOrders'][0])
    {
        $request = $this->listOrdersRequest($page, $results, $shippo_api_version, $order_status, $shop_app, $start_date, $end_date, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\OrderPaginatedList',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        'array<string,mixed>',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\OrderPaginatedList',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\OrderPaginatedList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,mixed>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listOrdersAsync
     *
     * List all orders
     *
     * @param  int|null $page The page number you want to select (optional, default to 1)
     * @param  int|null $results The number of results to return per page (max 100) (optional, default to 25)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  \OpenAPI\Client\Model\OrderStatusEnum[]|null $order_status Filter orders by order status (optional)
     * @param  \OpenAPI\Client\Model\OrderShopAppEnum|null $shop_app Filter orders by shop app (optional)
     * @param  string|null $start_date Filter orders created after the input date and time (ISO 8601 UTC format).  This is based on the  &#x60;placed_at&#x60; field, meaning when the order has been placed, not when the order object was created. (optional)
     * @param  string|null $end_date Filter orders created before the input date and time (ISO 8601 UTC format).  This is based on the  &#x60;placed_at&#x60; field, meaning when the order has been placed, not when the order object was created. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listOrders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listOrdersAsync($page = 1, $results = 25, $shippo_api_version = null, $order_status = null, $shop_app = null, $start_date = null, $end_date = null, string $contentType = self::contentTypes['listOrders'][0])
    {
        return $this->listOrdersAsyncWithHttpInfo($page, $results, $shippo_api_version, $order_status, $shop_app, $start_date, $end_date, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listOrdersAsyncWithHttpInfo
     *
     * List all orders
     *
     * @param  int|null $page The page number you want to select (optional, default to 1)
     * @param  int|null $results The number of results to return per page (max 100) (optional, default to 25)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  \OpenAPI\Client\Model\OrderStatusEnum[]|null $order_status Filter orders by order status (optional)
     * @param  \OpenAPI\Client\Model\OrderShopAppEnum|null $shop_app Filter orders by shop app (optional)
     * @param  string|null $start_date Filter orders created after the input date and time (ISO 8601 UTC format).  This is based on the  &#x60;placed_at&#x60; field, meaning when the order has been placed, not when the order object was created. (optional)
     * @param  string|null $end_date Filter orders created before the input date and time (ISO 8601 UTC format).  This is based on the  &#x60;placed_at&#x60; field, meaning when the order has been placed, not when the order object was created. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listOrders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listOrdersAsyncWithHttpInfo($page = 1, $results = 25, $shippo_api_version = null, $order_status = null, $shop_app = null, $start_date = null, $end_date = null, string $contentType = self::contentTypes['listOrders'][0])
    {
        $returnType = '\OpenAPI\Client\Model\OrderPaginatedList';
        $request = $this->listOrdersRequest($page, $results, $shippo_api_version, $order_status, $shop_app, $start_date, $end_date, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listOrders'
     *
     * @param  int|null $page The page number you want to select (optional, default to 1)
     * @param  int|null $results The number of results to return per page (max 100) (optional, default to 25)
     * @param  string|null $shippo_api_version Optional string used to pick a non-default API version to use. See our &lt;a href&#x3D;\&quot;https://docs.goshippo.com/docs/api_concepts/apiversioning/\&quot;&gt;API version&lt;/a&gt; guide. (optional)
     * @param  \OpenAPI\Client\Model\OrderStatusEnum[]|null $order_status Filter orders by order status (optional)
     * @param  \OpenAPI\Client\Model\OrderShopAppEnum|null $shop_app Filter orders by shop app (optional)
     * @param  string|null $start_date Filter orders created after the input date and time (ISO 8601 UTC format).  This is based on the  &#x60;placed_at&#x60; field, meaning when the order has been placed, not when the order object was created. (optional)
     * @param  string|null $end_date Filter orders created before the input date and time (ISO 8601 UTC format).  This is based on the  &#x60;placed_at&#x60; field, meaning when the order has been placed, not when the order object was created. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listOrders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listOrdersRequest($page = 1, $results = 25, $shippo_api_version = null, $order_status = null, $shop_app = null, $start_date = null, $end_date = null, string $contentType = self::contentTypes['listOrders'][0])
    {


        if ($results !== null && $results > 100) {
            throw new \InvalidArgumentException('invalid value for "$results" when calling OrdersApi.listOrders, must be smaller than or equal to 100.');
        }
        






        $resourcePath = '/orders';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $results,
            'results', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order_status,
            'order_status[]', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $shop_app,
            'shop_app', // param base name
            'OrderShopAppEnum', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_date,
            'start_date', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $end_date,
            'end_date', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($shippo_api_version !== null) {
            $headerParams['SHIPPO-API-VERSION'] = ObjectSerializer::toHeaderValue($shippo_api_version);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
