<?php
/**
 * ServiceLevelDeutschePostEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelDeutschePostEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | deutsche_post_postkarte | Postkarte| | deutsche_post_standardbrief | Standardbrief| | deutsche_post_kompaktbrief | Kompaktbrief| | deutsche_post_grossbrief | Grossbrief| | deutsche_post_maxibrief | Maxibrief| | deutsche_post_maxibrief_plus | Maxibrief Plus| | deutsche_post_warenpost_international_xs | Warenpost International XS| | deutsche_post_warenpost_international_s | Warenpost International S| | deutsche_post_warenpost_international_m | Warenpost International M| | deutsche_post_warenpost_international_l | Warenpost International L|
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelDeutschePostEnum
{
    /**
     * Possible values of this enum
     */
    public const DEUTSCHE_POST_POSTKARTE = 'deutsche_post_postkarte';

    public const DEUTSCHE_POST_STANDARDBRIEF = 'deutsche_post_standardbrief';

    public const DEUTSCHE_POST_KOMPAKTBRIEF = 'deutsche_post_kompaktbrief';

    public const DEUTSCHE_POST_GROSSBRIEF = 'deutsche_post_grossbrief';

    public const DEUTSCHE_POST_MAXIBRIEF = 'deutsche_post_maxibrief';

    public const DEUTSCHE_POST_MAXIBRIEF_PLUS = 'deutsche_post_maxibrief_plus';

    public const DEUTSCHE_POST_WARENPOST_INTERNATIONAL_XS = 'deutsche_post_warenpost_international_xs';

    public const DEUTSCHE_POST_WARENPOST_INTERNATIONAL_S = 'deutsche_post_warenpost_international_s';

    public const DEUTSCHE_POST_WARENPOST_INTERNATIONAL_M = 'deutsche_post_warenpost_international_m';

    public const DEUTSCHE_POST_WARENPOST_INTERNATIONAL_L = 'deutsche_post_warenpost_international_l';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DEUTSCHE_POST_POSTKARTE,
            self::DEUTSCHE_POST_STANDARDBRIEF,
            self::DEUTSCHE_POST_KOMPAKTBRIEF,
            self::DEUTSCHE_POST_GROSSBRIEF,
            self::DEUTSCHE_POST_MAXIBRIEF,
            self::DEUTSCHE_POST_MAXIBRIEF_PLUS,
            self::DEUTSCHE_POST_WARENPOST_INTERNATIONAL_XS,
            self::DEUTSCHE_POST_WARENPOST_INTERNATIONAL_S,
            self::DEUTSCHE_POST_WARENPOST_INTERNATIONAL_M,
            self::DEUTSCHE_POST_WARENPOST_INTERNATIONAL_L
        ];
    }
}


