<?php
/**
 * ServiceLevelChronopostEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelChronopostEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | chronopost_13 | Chrono 13| | chronopost_10 | Chrono 10| | chronopost_18| Chrono 18| | chronopost_relais_fr | Chrono Point Relais| | chronopost_classic | Chrono Classic International| | chronopost_express | Chrono Express International|
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelChronopostEnum
{
    /**
     * Possible values of this enum
     */
    public const CHRONOPOST_13 = 'chronopost_13';

    public const CHRONOPOST_10 = 'chronopost_10';

    public const CHRONOPOST_18 = 'chronopost_18';

    public const CHRONOPOST_RELAIS_FR = 'chronopost_relais_fr';

    public const CHRONOPOST_CLASSIC = 'chronopost_classic';

    public const CHRONOPOST_EXPRESS = 'chronopost_express';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CHRONOPOST_13,
            self::CHRONOPOST_10,
            self::CHRONOPOST_18,
            self::CHRONOPOST_RELAIS_FR,
            self::CHRONOPOST_CLASSIC,
            self::CHRONOPOST_EXPRESS
        ];
    }
}


