<?php
/**
 * ServiceLevelColissimoEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelColissimoEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | colissimo_home | Domicile| | colissimo_pick_up_point | Point Retrait| | colissimo_return_mainland_france | Retour France|
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelColissimoEnum
{
    /**
     * Possible values of this enum
     */
    public const COLISSIMO_HOME = 'colissimo_home';

    public const COLISSIMO_PICK_UP_POINT = 'colissimo_pick_up_point';

    public const COLISSIMO_RETURN_MAINLAND_FRANCE = 'colissimo_return_mainland_france';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::COLISSIMO_HOME,
            self::COLISSIMO_PICK_UP_POINT,
            self::COLISSIMO_RETURN_MAINLAND_FRANCE
        ];
    }
}


