<?php
/**
 * ServiceLevelGLSUSEnumTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ServiceLevelGLSUSEnumTest Class Doc Comment
 *
 * @category    Class
 * @description |Token | Service name| |:---|:---| | gls_us_cps | GSO Ground| | gls_us_eps | Early Priority Overnight| | gls_us_ess | Early Saturday Delivery| | gls_us_nps | Noon Priority Overnight| | gls_us_pds | Priority Overnight| | gls_us_sds | Saturday Delivery|
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ServiceLevelGLSUSEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ServiceLevelGLSUSEnum"
     */
    public function testServiceLevelGLSUSEnum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
