<?php
/**
 * ServiceLevelDHLExpressEnumTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ServiceLevelDHLExpressEnumTest Class Doc Comment
 *
 * @category    Class
 * @description |Token | Service name| |:---|:---| | dhl_express_domestic_express_doc | Domestic Express Doc| | dhl_express_economy_select_doc | Economy Select Doc| | dhl_express_worldwide_nondoc | Express Worldwide Nondoc| | dhl_express_worldwide_doc | Express Worldwide Doc| | dhl_express_worldwide | Worldwide| | dhl_express_worldwide_eu_doc | Express Worldwide EU Doc| | dhl_express_break_bulk_express_doc | Break Bulk Express Doc| | dhl_express_express_9_00_nondoc | Express 9:00 NonDoc| | dhl_express_economy_select_nondoc | Economy Select NonDoc| | dhl_express_break_bulk_economy_doc | Break Bulk Economy Doc| | dhl_express_express_9_00_doc | Express 9:00 Doc| | dhl_express_express_10_30_doc | Express 10:30 Doc| | dhl_express_express_10_30_nondoc | Express 10:30 NonDoc| | dhl_express_express_12_00_doc | Express 12:00 Doc| | dhl_express_europack_nondoc | Europack NonDoc| | dhl_express_express_envelope_doc | Express Envelope Doc| | dhl_express_express_12_00_nondoc | Express 12:00 NonDoc| | dhl_express_express_12_doc | Domestic Express 12:00| | dhl_express_worldwide_b2c_doc | Express Worldwide (B2C) Doc| | dhl_express_worldwide_b2c_nondoc | Express Worldwide (B2C) NonDoc| | dhl_express_medical_express | Medical Express| | dhl_express_express_easy_nondoc | Express Easy NonDoc|
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ServiceLevelDHLExpressEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ServiceLevelDHLExpressEnum"
     */
    public function testServiceLevelDHLExpressEnum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
