<?php
/**
 * ServiceLevelAustraliaPostEnumTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ServiceLevelAustraliaPostEnumTest Class Doc Comment
 *
 * @category    Class
 * @description |Token | Service name| |:---|:---| | australia_post_express_post | Express Post| | australia_post_parcel_post | Parcel Post| | australia_post_pack_and_track_international | Pack and Track International| | australia_post_international_airmail | International Airmail| | australia_post_express_post_international | Express Post International| | australia_post_express_courier_international | Express Courier International| | australia_post_international_express | International Express| | australia_post_international_standard | International Standard| | australia_post_international_economy | International Economy| | australia_post_parcel_post_return | Parcel Post Return|
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ServiceLevelAustraliaPostEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ServiceLevelAustraliaPostEnum"
     */
    public function testServiceLevelAustraliaPostEnum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
